import type { ReactNode } from "react";
import { cn } from "../../lib/cn";

/**
 * The label / hint / error scaffolding shared by Input and Select, so both
 * wire `aria-describedby` and `aria-invalid` the same way and neither has to
 * remember to.
 *
 * When there is an error the hint is replaced rather than stacked: two lines of
 * small text under a control is where people stop reading either.
 */
export interface FieldProps {
  /** Id of the control this labels — supplied by the caller via `useId`. */
  htmlFor: string;
  label: string;
  hint?: string;
  error?: string;
  required?: boolean;
  /** Ids for aria-describedby, generated by `fieldIds`. */
  hintId: string;
  errorId: string;
  children: ReactNode;
  className?: string;
}

export function fieldIds(id: string) {
  return { hintId: `${id}-hint`, errorId: `${id}-error` };
}

/**
 * The describedby value a control should carry, given which messages are
 * actually rendered. Returns undefined rather than an empty string so the
 * attribute is omitted entirely.
 */
export function describedBy(
  ids: { hintId: string; errorId: string },
  hint: string | undefined,
  error: string | undefined,
): string | undefined {
  if (error) return ids.errorId;
  if (hint) return ids.hintId;
  return undefined;
}

export function Field({
  htmlFor,
  label,
  hint,
  error,
  required,
  hintId,
  errorId,
  children,
  className,
}: FieldProps) {
  return (
    <div className={cn("flex flex-col gap-1", className)}>
      <label htmlFor={htmlFor} className="text-xs font-medium text-muted">
        {label}
        {required ? (
          <span aria-hidden="true" className="ml-1 text-danger">
            *
          </span>
        ) : null}
      </label>

      {children}

      {error ? (
        <p id={errorId} className="text-xs text-danger">
          {error}
        </p>
      ) : hint ? (
        <p id={hintId} className="text-xs text-muted">
          {hint}
        </p>
      ) : null}
    </div>
  );
}

/** Shared box styling for anything that behaves like a text control. */
export const controlBase = cn(
  "w-full rounded-md border bg-surface px-3 py-2 text-sm text-text",
  "transition-colors duration-100",
  "placeholder:text-faint",
  "disabled:cursor-not-allowed disabled:bg-surface-hover disabled:text-faint",
);

export function controlBorder(hasError: boolean): string {
  return hasError
    ? "border-danger focus-visible:outline-danger"
    : "border-border-strong";
}
